#! /bin/sh
# /etc/init.d/webserver 

#sudo chmod 755 /etc/init.d/webserver
#sudo /etc/init.d/webserver start
#sudo /etc/init.d/webserver stop

#Add to system services:
#sudo update-rc.d webserver defaults

#Delete from system services:
#sudo update-rc.d -f webserver remove

### BEGIN INIT INFO
# Provides:          webserver
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting webserver"
    # run application you want to start
    #/usr/local/bin/noip2
    /home/pi/py_web/webserver.py
    ;;
  stop)
    echo "Stopping webserver"
    # kill application you want to stop
    killall webserver.py
    ;;
  *)
    echo "Usage: /etc/init.d/noip {start|stop}"
    exit 1
    ;;
esac

exit 0
